CREATE TABLE IF NOT EXISTS users
(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

DELIMITER //
CREATE PROCEDURE add_user(IN p_name VARCHAR(100))
BEGIN
  INSERT INTO users(name) VALUES (p_name);
END//
DELIMITER ;
